### PR TITLE
Intro to Statsmodels and Sklearn V_1

### PR DESCRIPTION
**Pull request by abulshariff**
Hello @vsathwikm,
This is Abul Shariff.
So please take a look at my first attempt.
I tried to go in as much detail as possible 
and also I tried to make as simple as possible.
Please advice as to where I can make it better.
Thank you

### CODE REVIEW

**Comment by vsathwikm** [comment]
@abulshariff  Excellent stuff! Great explanations and good details. This is level of detail is perfect and easy for people to understand. Keep it up! The only thing I would want you to do now is to add a little more examples/practice exercises for each of the functions you have introduced, so users get to practice on it. Great job!

@manirv  Please provide your review as well. I think this is a really good job!

@dheb20  You may look at the explanations. This is good detail. For eg. In the first section he says, stats models is a module and scikit-learn is a library and then immediately defines what a module is and what a library is...This is what we need to follow. Be clear and explain everything assuming user knows nothing.

**Comment by vsathwikm** [comment]
@abulshariff  You can also add side headings for each of the functions you are introducing. That will give a good idea of sections being dealt with.

**Comment by abulshariff** [comment]
Hello @sathwik@colaberry.com <sathwik@colaberry.com>,
Can you give me an example for side headings ?
Thank you
AS

**Comment by abulshariff** [comment]
Hello @sathwik@colaberry.com <sathwik@colaberry.com>,
Thank you for the feedback.
*more examples/practice exercises for each of the functions*
does this mean for instance the intermediary functions I am using may be
add
some more functionality for those ?

and also I feel like i can use some reference for statsmodel my knowledge
on statistics is a little week
AS

**Comment by sathwik** [comment]
Sorry, you have contacted the wrong person.

**Comment by vsathwikm** [comment]
@abulshariff 

1. Maintain consistency in naming the 'Statsmodel' library. Address it as 'Statsmodels' everywhere, except in code, where it would be all lower case. Same for 'Sklearn'
2. In 'Introduction to Statsmodels...' section, last couple of lines "But what is a classifier ? And how is the data put in a sequence which can be available for further analysis ?" continue on this and explain further. Tell the learner that Classifier is a prediction model and sklearn helps us build one. And what is the role that Statsmodels would be playing in this, Descriptive Statistics is what is covered mainly by Statsmodels, apart from other data analysis and statistics functions.
3. Please do a spell check. One place statsmodels is written as statsmoels.
4. Before using Guerry dataset describe a bit about what that dataset consists of and the background about the data itself.
5. Before you add code for any function, put the explanation before code. For e.g., dmatrices() function explanation should come before the code. Also, a simple side heading would be The dmatrices function or 'Converting a Data Frame to Matrices'.
6. The Code and Exercises in later sections of the notebook can be further formatted so as to showcase specific blocks of code and their functioning (i.e., code for fitting model, code for predicting values, code for validation etc.) as of now its split much more granularly, i.e., even print statements are in separate blocks, which is not too ideal.

**Comment by abulshariff** [comment]
@vsathwikm @pawan-nandakishore @manirv 
Hello guys I have just pushed a V2.1 to Into to Statsmodels and sklearn. 
My changes were based off of Sathwik's comments. I hope I did justice with it 
Thank you

**Pull request merged**
